### ISSUE TITLE
Written document?

### ISSUE THREAD

**Issue by nshervt** [sbrodehl/MD-AlanineDipeptide#1]
Is there a paper or a written document that accompanies this repository? The plots seem interesting and I was wondering if I can read more about what you are doing in this work. Thanks!

**Comment by sbrodehl** [comment]
Hi @nshervt ,

Thanks for reaching out, but unfortunately I can’t find any related documents for the project.

Anyway, I think it is a good idea to update the readme with the available images and add some text to it, so that others as well understand the work. :)

Best,
Sebastian

**Comment by nshervt** [comment]
Thanks @sbrodehl. Looking forward to that!

**Comment by sbrodehl** [comment]
Hey @nshervt ,

I just updated the README.md with a walkthrough which covers all the steps done in the project.
For more information please refer to the given references.

Best,
Sebatian

**Comment by nshervt** [comment]
Thanks @sbrodehl! I appreciate that.
